CREATE TABLE `result` (
  `stock_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `stock_code` VARCHAR(10) DEFAULT NULL COMMENT '股票代码',
  `stock_price` DOUBLE DEFAULT NULL COMMENT '股票价格',
  `stategy_id` INT(11) DEFAULT NULL COMMENT '策略ID',
  `total_value` DOUBLE DEFAULT NULL COMMENT '1分钟内成交量',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`stock_id`)
) ENGINE=MYISAM AUTO_INCREMENT=459 DEFAULT CHARSET=utf8
